[project]
name = "werewolf-llm"
version = "0.1.0"
description = "A project to train an LLM to play One Night Ultimate Werewolf."
authors = [{ name = "Lawrence Forman", email = "me@merklejerk.com" }]
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.11.7",
]

[project.scripts]
gen-sft = "werewolf_llm.generate_sft_data:main_sync"
train = "werewolf_llm.train:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/werewolf_llm"]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.python.org/simple"

[tool.uv.sources]
markupsafe = { index = "pypi" }

[tool.uv]
override-dependencies = [
    "torch; sys_platform == 'never'",
    "torchaudio; sys_platform == 'never'",
    "torchvision; sys_platform == 'never'",
    "triton; sys_platform == 'never'",
    "vllm; sys_platform == 'never'",
    "bitsandbytes; sys_platform == 'never'",
]

[dependency-groups]
training = [
    "accelerate>=1.9.0",
    "datasets>=4.0.0",
    "evaluate>=0.4.5",
    "numpy>=2.0.2",
    "pandas>=2.3.1",
    "peft>=0.16.0",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
    "transformers>=4.53.2",
    "trl>=0.9.4",
    "pydantic>=2.11.7",
]
