services:
  llm_dev:
    extends:
      file: docker-compose.cpu.yml
      service: llm_dev
    build:
      args:
        BASE_IMAGE: "rocm/vllm:latest"
    environment:
      - BACKEND=rocm
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video